### ISSUE TITLE
OPTION to close window instead of killing the process

### ISSUE THREAD

**Issue by PeterPanino** [SwiftExpat/Deputy#1]
Instead of killing the process, there should be an option to CLOSE ITS MAIN WINDOW.

**Comment by SwiftExpat** [comment]
Would closing its main window call free on some object (database connection)? What would be the minimal working sample?

**Comment by PeterPanino** [comment]
Well, there's the `CloseWindow` API call in **Winapi.Windows**.

AFAIK, `CloseWindow` indeed calls Free on all objects owned by the main window and thus by the process.

BTW, thanks for Deputy. I have long wished for such an expert.

**Comment by PeterPanino** [comment]
To get the main window handle, there are different solutions:
1. The app could simply store the value of its Form.Handle in a public variable accessible by Deputy.
2. A way that is more tricky: Get the window handle - look at OpenProcess

**Comment by SwiftExpat** [comment]
I will try to work up something using EnumWindows, QuickLib from Exilon has at least a starting point in QuickLib.Process, but on first try that did not work.  

I modified my VCL demo output a debug string on datamodule destroy and form destroy. That should confirm that the destructors get called.

Do you have a splash screen that stays open or just a child form(s)?

**Comment by SwiftExpat** [comment]
@PeterPanino  I believe the logic for identifying the main form is complete, can you give it a try against your application and verify that it closes correctly?
There is a video and tool here:
https://github.com/SwiftExpat/Deputy/releases/tag/2.4.5

Just run ProcTreeVCL and edit the text box to your app name.  The code essentially finds the window and publishes wm_close but you can review it here: https://github.com/SwiftExpat/Deputy/tree/main/DevTools/ProcTreeVCL

**Comment by SwiftExpat** [comment]
On the terminate logic, how long should Deputy wait for the app to close? I am thinking wait a few seconds, configurable, then if the app does not close, terminate it. Or message with a notification and stop the build in the IDE.

**Comment by SwiftExpat** [comment]
If the app is running with report memory on shutdown, Deputy should watch for that window. Options could be:

1. terminate on window showing (Sometimes the leak report is very slow, whats the best case to re-produce)
2. cancel the build / run and let the user deal with the app.

**Comment by SwiftExpat** [comment]
Most of the close and poll for mem leak is done. The logic still needs a global timeout to ensure the IDE returns at some point.

**Comment by SwiftExpat** [comment]
2.5.1 addresses close functionality.  Go to Tools, SE Deputy, Kill process settings.
![image](https://user-images.githubusercontent.com/76655220/177429337-1c8a859e-7516-49d4-b638-7caaa87048b8.png)

You can choose to terminate or close, and then choose your actions for the memory leak window, close and optionally copy the memory leak
